import type { Metadata } from "next";
import { Inter, Nunito} from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--inter",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tomang Durian",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {

  return (
    <html>
      <body
        className={`${inter.variable} ${nunito.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
