import type { Metadata } from "next";
import { Raleway, Roboto } from "next/font/google";
import "../globals.css";

import Navigation from "@/components/navigation";

import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getMessages, setRequestLocale } from "next-intl/server";

const raleway = Raleway({
  variable: "--raleway",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>
}) {
  const messages = getMessages();

  const { locale } = await params;


  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale)

  return (
    <html lang={locale}>
      <body
        className={`${raleway.variable} ${roboto.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
